# Copyright (c) 2016-2020 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: Advit Deepak's Awesome Dashboard
site_url: "https://advitdeepak.github.io/about-advit/"
site_author: Advit Deepak
site_description: >-
  Hello, hello! This is a small, digital repository about me, <strong>Advit Deepak</strong>.
  Feel free to explore and learn a little bit more about <strong>who I am</strong>, <strong>what I do</strong>, and the
  <strong>things I love</strong>. From <em>LEGO door-closers</em> to <em>touchless technology</em>, who knows what you'll find! 😉😄

# Repository
repo_name: about-advit
repo_url: https://github.com/AdvitDeepak/about-advit # ADD THIS LATER
edit_uri: "" # ADD THIS LATER

# Copyright
copyright: Copyright &copy; 2021 Advit Deepak

# Configuration
theme:
  name: null
  custom_dir: material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - tabs
    #- instant
  palette:
    scheme: default
    primary: light-blue
    accent: light-blue


  font:
    text: Quicksand
    code: Roboto Mono
  favicon: assets/favicon32.png
  icon:
    logo: logo

# Customization
extra:
  analytics: #
    provider: google
    property: G-43LNBYJX9X

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/AdvitDeepak
    - icon: fontawesome/brands/medium
      link: https://advit-deepak.medium.com/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCc7G2dvnfcEOH9mQgQ5iAPQ
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/advitdeepak/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/advitdeepak/

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/feedback.js

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md

  - About Me:
    - Where to Start?: 01_about-me.md
    - Exciting Education: 01_education.md
    - Work & Volunteering: 01_experience.md

  - Projects:
    - Academic Projects: 02_projects-01.md
    - TigerGraph Projects: 02_projects-02.md
    - Misc/D-I-Y Projects: 02_projects-03.md

  - Interests:
    - Interests: 03_awesome.md

  - Connect:
    - Connect: 04_community.md
